# This is a TOML file
# Lines starting with a # are comments and do not affect
# anything. They are simply notes.

# Some things you should know about TOML:
#       - Text fields must be wrapped in quotes: 'text'
#       - Lists get wrapped in square brackets and items
#         in them are seperated by commas
# list_of_text_fields = ['example', 'text']

# WHEN EDITING THIS FILE, ONLY EDIT THINGS ON THE RIGHT
# SIDE OF AN ASSIGNMENT (ONLY THE STUFF AFTER AN EQUALS SIGN)

[settings]
# Provide a list of holes to evaluate
# Eg; hole_selections = ['CANDD017', 'CANDD018']
# Leave as ['*'] to calculate all holes
	
	hole_selections = ['*']
	queries_to_run = ['*']
	seperate_assay_files = false

# Path to the main data CSV. This will generally be the
# rank 1 export from the main database

	exported_data_path = 'Drilling_Samples_R1.csv'

# The column names of some key field as described in
# the specified spreadsheet

	sample_id_column_name = 'SampleID'
	hole_id_column_name = 'Hole number'

# The location to store a database cache
# Don't touch unless you know what you are doing
cache_location = './cache'

[[assays]]
	element = "Cu"

# This must be the unit used in the database for this element.
# If the database contains multiple units for the same element,
# choose the unit you consider to be the most accurate/reliable
	
	base_unit = "%" 

# This is the unit you want the output reported in.
# A conversion will be performed automatically

	reported_unit = "%"

# The cutoff values to be used to calculate intercepts.
# THIS MUST BE IN TERMS OF THE BASE UNIT SPECIFIED ABOVE

	cutoffs = [0.1, 0.5, 1]

# This is a list of the secondary elements you would like to
# have calculated against the primary

co_analytes = [
    {element = "Au", base_unit = "ppm", reported_unit = "ppm"},
    {element = "Ag", base_unit = "ppm", reported_unit = "ppm"},
    {element = "Co", base_unit = "ppm", reported_unit = "ppm"},
    {element = "Zn", base_unit = "ppm", reported_unit = "ppm"}
]
# Don't touch this
[logging]
report_errors = true
log_level = 'ERROR_ONLY'