[settings]
hole_selections = [ "*",]
queries_to_run = [ "*",]
seperate_assay_files = false
exported_data_path = "Drilling_Samples_R1.csv"
sample_id_column_name = "SampleID"
hole_id_column_name = "Hole number"
cache_location = "./cache"

[logging]
report_errors = true
log_level = "ERROR_ONLY"
