# List of elements by IUPAC specified names
elements = {
  "Ac": "Actinium",
  "Ag": "Silver",
  "Al": "Aluminium",
  "Am": "Americium",
  "Ar": "Argon",
  "As": "Arsenic",
  "At": "Astatine",
  "Au": "Gold",
  "B": "Boron",
  "Ba": "Barium",
  "Be": "Beryllium",
  "Bh": "Bohrium",
  "Bi": "Bismuth",
  "Bk": "Berkelium",
  "Br": "Bromine",
  "C": "Carbon",
  "Ca": "Calcium",
  "Cd": "Cadmium",
  "Ce": "Cerium",
  "Cf": "Californium",
  "Cl": "Chlorine",
  "Cm": "Curium",
  "Cn": "Copernicium",
  "Co": "Cobalt",
  "Cr": "Chromium",
  "Cs": "Cesium",
  "Cu": "Copper",
  "Db": "Dubnium",
  "Ds": "Darmstadtium",
  "Dy": "Dysprosium",
  "Er": "Erbium",
  "Es": "Einsteinium",
  "Eu": "Europium",
  "F": "Fluorine",
  "Fe": "Iron",
  "Fl": "Flerovium",
  "Fm": "Fermium",
  "Fr": "Francium",
  "Ga": "Gallium",
  "Gd": "Gadolinium",
  "Ge": "Germanium",
  "H": "Hydrogen",
  "He": "Helium",
  "Hf": "Hafnium",
  "Hg": "Mercury",
  "Ho": "Holmium",
  "Hs": "Hassium",
  "I": "Iodine",
  "In": "Indium",
  "Ir": "Iridium",
  "K": "Potassium",
  "Kr": "Krypton",
  "La": "Lanthanum",
  "Li": "Lithium",
  "Lr": "Lawrencium",
  "Lu": "Lutetium",
  "Lv": "Livermorium",
  "Mc": "Moscovium",
  "Md": "Mendelevium",
  "Mg": "Magnesium",
  "Mn": "Manganese",
  "Mo": "Molybdenum",
  "Mt": "Meitnerium",
  "N": "Nitrogen",
  "Na": "Sodium",
  "Nb": "Niobium",
  "Nd": "Neodymium",
  "Ne": "Neon",
  "Nh": "Nihonium",
  "Ni": "Nickel",
  "No": "Nobelium",
  "Np": "Neptunium",
  "O": "Oxygen",
  "Og": "Oganesson",
  "Os": "Osmium",
  "P": "Phosphorus",
  "Pa": "Protactinium",
  "Pb": "Lead",
  "Pd": "Palladium",
  "Pm": "Promethium",
  "Po": "Polonium",
  "Pr": "Praseodymium",
  "Pt": "Platinum",
  "Pu": "Plutonium",
  "Ra": "Radium",
  "Rb": "Rubidium",
  "Re": "Rhenium",
  "Rf": "Rutherfordium",
  "Rg": "Roentgenium",
  "Rh": "Rhodium",
  "Rn": "Radon",
  "Ru": "Ruthenium",
  "S": "Sulfur",
  "Sb": "Antimony",
  "Sc": "Scandium",
  "Se": "Selenium",
  "Sg": "Seaborgium",
  "Si": "Silicon",
  "Sm": "Samarium",
  "Sn": "Tin",
  "Sr": "Strontium",
  "Ta": "Tantalum",
  "Tb": "Terbium",
  "Tc": "Technetium",
  "Te": "Tellurium",
  "Th": "Thorium",
  "Ti": "Titanium",
  "Tl": "Thallium",
  "Tm": "Thulium",
  "Ts": "Tennnessine",
  "U": "Uranium",
  "V": "Vanadium",
  "W": "Tungsten",
  "Xe": "Xenon",
  "Y": "Yttrium",
  "Yb": "Ytterbium",
  "Zn": "Zinc",
  "Zr": "Zirconium"
}

compounds = {
  "(C6H10O5)n": "Cellulose",
  "(C8H8)n": "Polystyrene",
  "(Na2O)x·SiO2": "Sodium silicate",
  "(NH4)2CO3": "Ammonium carbonate",
  "(NH4)2O": "Ammonium oxide",
  "(NH4)2S2O8": "Ammonium persulfate",
  "(NH4)2SO4": "Ammonium sulfate",
  "(NH4)3PO4": "Ammonium phosphate",
  "Ag2CO3": "Silver carbonate",
  "Ag2O": "Silver oxide",
  "Ag3PO4": "Silver phosphate",
  "AgC2H3O2": "Silver acetate",
  "AgCl": "Silver chloride",
  "AgNO3": "Silver nitrate",
  "Al(OH)3": "Aluminium hydroxide",
  "Al2(SO4)3": "Aluminium sulfate",
  "Al2O3": "Aluminum oxide",
  "Al2S3": "Aluminum sulfide",
  "AlBr3": "Aluminum bromide",
  "AlF3": "Aluminum fluoride",
  "AlPO4": "Aluminum phosphate",
  "Ba(NO3)2": "Barium nitrate",
  "Ba(OH)2": "Barium hydroxide",
  "BaBr2": "Barium bromide",
  "BaCl2": "Barium chloride",
  "BaCO3": "Barium carbonate",
  "BaF2": "Barium fluoride",
  "BaI2": "Barium iodide",
  "BaO": "Barium oxide",
  "BaSO4": "Barium sulfate",
  "Br2": "Diatomic Bromine",
  "BrO3": "Bromate",
  "C10H12O2": "Eugenol",
  "C12H22O11": "Maltose",
  "C16H18ClN3S": "Methylene blue",
  "C18H36O2": "Stearic acid",
  "C20H14O4": "Phenolphthalein",
  "C27H28Br2O5S": "Bromothymol Blue",
  "C27H36N2O10": "Polyurethane Foam",
  "C2Cl4": "Tetrachloroethylene",
  "C2H2": "Acetylene",
  "C2H3N": "Acetonitrile",
  "C2H3NaO2": "Sodium acetate",
  "C2H3O2Cl": "Chloroacetic acid",
  "C2H3O2NH4": "Ammonium acetate",
  "C2H4": "Ethylene",
  "C2H4O": "Acetaldehyde",
  "C2H5NO": "Acetamide",
  "C2H5OH": "Ethanol",
  "C2H6": "Ethane",
  "C2H6Na4O12": "Sodium Percarbonate",
  "C2H6O2": "Ethylene glycol",
  "C2H6OS": "Dimethyl sulfoxide",
  "C2HCl3O2": "Trichloroacetic acid",
  "C2O42": "Oxalate",
  "C3H6O": "Acetone",
  "C3H6O2": "Methyl acetate",
  "C3H6O3": "Lactic acid",
  "C3H7NO2": "Urethane",
  "C3H8": "Propane",
  "C3H8O3": "Glycerol",
  "C4H10": "Butane",
  "C4H4O4": "Maleic acid",
  "C4H4O6KNa·4H2O": "Sodium potassium tartrate",
  "C4H6O4Ca": "Calcium acetate",
  "C4H6O4Ni": "Nickel acetate",
  "C4H6O6": "Tartaric acid",
  "C4H8N2O2": "Dimethylglyoxime",
  "C4H8O": "Methyl Ethyl Ketone",
  "C4H8O2": "Butanoic acid",
  "C5H5N": "Pyridine",
  "C5H8NO4Na": "Monosodium Glutamate",
  "C6H12N4": "Hexamine",
  "C6H12O6": "Fructose",
  "C6H14": "Hexane",
  "C6H14O6": "Mannitol",
  "C6H4Cl2": "Para dichlorobenzene",
  "C6H5": "Phenyl",
  "C6H6": "Benzene",
  "C6H6O": "Phenol",
  "C6H6O2": "Resorcinol",
  "C6H8O6": "Ascorbic acid",
  "C6H8O7": "Citric acid",
  "C76H52O46": "Tannic acid",
  "C7H6O2": "Benzoic acid",
  "C7H6O3": "Salicylic Acid",
  "C8H10": "Xylene",
  "Ca(NO3)2": "Calcium nitrate",
  "Ca(OH)2": "Calcium hydroxide",
  "Ca3(PO4)2": "Calcium phosphate",
  "CaC2": "Calcium Carbide",
  "CaCl2": "Calcium Chloride",
  "CaCO3": "Calcium carbonate",
  "CaH2": "Calcium hydride",
  "CaI2": "Calcium iodide",
  "CaO": "Calcium oxide",
  "CCl4": "Carbon tetrachloride",
  "CH2Cl2": "Dichloromethane",
  "CH2O": "Formaldehyde",
  "CH3CO2K": "Potassium acetate",
  "CH3COO": "Acetate",
  "CH3COOH": "Acetic acid",
  "CH3OH": "Methanol",
  "CH4": "Methane",
  "CH4N2O": "Urea",
  "CHO3": "Bicarbonate",
  "Cl2": "Chlorine",
  "ClF3": "Chlorine Trifluoride",
  "ClO": "Hypochlorite",
  "CN": "Cyanide",
  "CO": "Carbon monoxide",
  "Cr2O3": "Chromic Oxide",
  "CrK2O4": "Potassium chromate",
  "CrO42-": "Chromate",
  "CS2": "Carbon Disulfide",
  "Cu(OH)2": "Copper Hydroxide",
  "Cu2O": "Copper(I) Oxide",
  "CuCl2": "Copper (II) chloride",
  "CuCO3": "Copper ii carbonate",
  "CuSO4": "Copper sulfate",
  "Fe2O3": "Iron oxide",
  "H2C2O4": "Oxalic acid",
  "H2CO3": "Carbonic acid",
  "H2CrO4": "Chromic acid",
  "H2O2": "Hydrogen peroxide",
  "H2S2O8": "Peroxydisulfuric Acid",
  "H2SO3": "Sulfurous acid",
  "H2SO4": "Sulfuric acid",
  "H3BO3": "Boric acid",
  "H3PO3": "Phosphorous Acid",
  "H3PO4": "Phosphoric acid",
  "HBr": "Hydrobromic acid",
  "HBrO": "Hypobromous acid",
  "HCl": "Hydrochloric acid",
  "HClO": "Hypochlorous acid",
  "HClO4": "Perchloric acid",
  "HCN": "Hydrocyanic acid",
  "HCOOH": "Formic Acid",
  "HgCl2": "Mercuric chloride",
  "HI": "Hydroiodic acid",
  "HIO": "Hypoiodous acid",
  "HNO2": "Nitrous acid",
  "HNO3": "Nitric acid",
  "HSO4": "Hydrogen sulfate",
  "K2CO3": "Potassium carbonate",
  "K2Cr2O7": "Dichromate",
  "K2HPO4": "Dipotassium Phosphate",
  "K2O": "Potassium oxide",
  "K2SO3": "Potassium sulfite",
  "K4Fe(CN)6": "Potassium Ferrocyanide",
  "KBr": "Potassium Bromide",
  "KCl": "Potassium chloride",
  "KClO": "Potassium hypochlorite",
  "KClO3": "Potassium chlorate",
  "KCN": "Potassium cyanide",
  "KF": "Potassium fluoride",
  "KH2PO4": "Monopotassium phosphate",
  "KHCO3": "Potassium bicarbonate",
  "KI": "Potassium iodide",
  "KIO3": "Potassium Iodate",
  "KMnO4": "Potassium Permanganate",
  "KNO2": "Potassium nitrite",
  "KNO3": "Potassium nitrate",
  "KOH": "Potassium hydroxide",
  "KSCN": "Potassium Thiocyanate",
  "Li2O": "Lithium oxide",
  "Li3PO4": "Lithium phosphate",
  "LiBr": "Lithium bromide",
  "LiCl": "Lithium chloride",
  "LiI": "Lithium iodide",
  "LiOH": "Lithium hydroxide",
  "Mg(NO3)2": "Magnesium nitrate",
  "Mg(OH)2": "Magnesium hydroxide",
  "Mg3(PO4)2": "Magnesium phosphate",
  "MgCl2": "Magnesium chloride",
  "MgCO3": "Magnesium carbonate",
  "MgI2": "Magnesium iodide",
  "MgO": "Magnesium oxide",
  "MgS": "Magnesium sulfide",
  "MgSO4": "Magnesium sulfate",
  "MnO": "Manganese(II) oxide",
  "MnO2": "Manganese dioxide",
  "N2H4": "Hydrazine",
  "N2O": "Dinitrogen monoxide",
  "N2O3": "Dinitrogen trioxide",
  "N2O5": "Dinitrogen Pentoxide",
  "Na2[B4O5(OH)4]·8H2O": "Sodium borate",
  "Na2CO3": "Sodium carbonate",
  "Na2Cr2O7": "Sodium dichromate",
  "Na2CrO4": "Sodium chromate",
  "Na2O": "Sodium oxide",
  "Na2O2": "Sodium peroxide",
  "Na2S": "Sodium sulfide",
  "Na2S2O3": "Sodium Thiosulfate",
  "Na2S2O5": "Sodium metabisulfite",
  "Na2SO3": "Sodium sulfite",
  "Na2SO4": "Sodium sulfate",
  "Na3C6H5O7": "Sodium citrate",
  "Na3N": "Sodium nitride",
  "Na3PO4": "Sodium phosphate",
  "NaBr": "Sodium bromide",
  "NaCl": "Sodium chloride",
  "NaClO": "Bleach",
  "NaClO3": "Sodium Chlorate",
  "NaCN": "Sodium cyanide",
  "NaF": "Sodium fluoride",
  "NaHCO3": "Sodium bicarbonate",
  "NaHSO4": "Sodium bisulfate",
  "NaI": "Sodium iodide",
  "NaNO2": "Sodium nitrite",
  "NaNO3": "Sodium nitrate",
  "NaOH": "Sodium hydroxide",
  "NH3": "Ammonia",
  "NH4Br": "Ammonium bromide",
  "NH4Cl": "Ammonium chloride",
  "NH4HCO3": "Ammonium bicarbonate",
  "NH4I": "Ammonium iodide",
  "NH4NO2": "Ammonium nitrite",
  "NH4NO3": "Ammonium nitrate",
  "NH4OH": "Ammonium hydroxide",
  "Ni(NO3)2": "Nickel nitrate",
  "NiSO4": "Nickel sulfate",
  "NO": "Nitrogen monoxide",
  "NO2": "Nitrite",
  "O3": "Ozone",
  "OH": "Hydroxide",
  "OH2": "Dihydrogen monoxide",
  "P2O5": "Phosphorus pentoxide",
  "Pb(C2H3O2)2": "Lead Acetate",
  "PbI2": "Lead iodide",
  "PbO2": "Lead (IV) oxide",
  "PCl3": "Phosphorus Trichloride",
  "PCl5": "Phosphorus pentachloride",
  "Pd2": "Palladium(2+)",
  "PI3": "Phosphorus Triiodide",
  "PO43-": "Phosphate ion",
  "Pt2": "Platinum(2+)",
  "SF6": "Sulfur Hexafluoride",
  "SiO2": "Silicon dioxide",
  "SnCl2": "Tin (II) chloride",
  "SnO2": "Tin Oxide",
  "SO2": "Sulfur dioxide",
  "SO3": "Sulfur trioxide",
  "SO42": "Sulfate ion",
  "Sr(NO3)2": "Strontium nitrate",
  "SrCl2": "Strontium chloride",
  "TiO2": "Titanium dioxide",
  "XeF2": "Xenon Difluoride",
  "Zn(CH3COO)2(H2O)2": "Zinc acetate",
  "Zn(NO3)2": "Zinc nitrate",
  "Zn(OH)2": "Zinc hydroxide",
  "Zn3(PO4)2": "Zinc phosphate",
  "ZnCl2": "Zinc chloride",
  "ZnCO3": "Zinc carbonate",
  "ZnI2": "Zinc iodide",
  "ZnS": "Zinc sulfide",
  "ZnSO4": "Zinc sulfate"
}

master = elements | compounds