[copper_assay]
element = "Cu"
base_unit = "ppm"
reported_unit = "%"
cutoffs = [ 0.1, 0.5, 1.0,]
[[copper_assay.co_analytes]]
element = "Au"
base_unit = "ppm"
reported_unit = "ppm"

[[copper_assay.co_analytes]]
element = "Ag"
base_unit = "ppm"
reported_unit = "ppm"

[[copper_assay.co_analytes]]
element = "Co"
base_unit = "ppm"
reported_unit = "ppm"

[[copper_assay.co_analytes]]
element = "Zn"
base_unit = "ppm"
reported_unit = "ppm"

[nickle_assay]
element = "Ni"
base_unit = "ppm"
reported_unit = "%"
cutoffs = [ 0.1, 0.5, 1.0,]
[[nickle_assay.co_analytes]]
element = "Cu"
base_unit = "ppm"
reported_unit = "ppm"

[[nickle_assay.co_analytes]]
element = "Co"
base_unit = "ppm"
reported_unit = "ppm"

[[nickle_assay.co_analytes]]
element = "Cr"
base_unit = "ppm"
reported_unit = "ppm"

[[nickle_assay.co_analytes]]
element = "Mg"
base_unit = "ppm"
reported_unit = "ppm"

[gold_assay]
element = "Au"
base_unit = "ppm"
reported_unit = "g/t"
cutoffs = [ 0.1, 0.5, 1.0,]
[[gold_assay.co_analytes]]
element = "Ag"
base_unit = "ppm"
reported_unit = "ppm"

[[gold_assay.co_analytes]]
element = "As"
base_unit = "ppm"
reported_unit = "ppm"

[[gold_assay.co_analytes]]
element = "Cu"
base_unit = "ppm"
reported_unit = "ppm"

[[gold_assay.co_analytes]]
element = "Sb"
base_unit = "ppm"
reported_unit = "ppm"

[lead_assay]
element = "Pb"
base_unit = "ppm"
reported_unit = "ppm"
cutoffs = [ 0.1, 0.5, 1.0,]
[[lead_assay.co_analytes]]
element = "Ag"
base_unit = "ppm"
reported_unit = "ppm"

[[lead_assay.co_analytes]]
element = "Au"
base_unit = "ppm"
reported_unit = "ppm"

